version: '3.9'
services:
  fit-friends.frontend:
    container_name: fit-friends.frontend
    restart: always
    image: fit-friends.frontend:latest
    environment:
      PORT: 5173
    ports:
      - "5173:5173"
    networks:
      - fit-friends.network

networks:
  fit-friends.network:
    driver: bridge
