import { StateType } from '../../types';
import { NameSpace } from '../../const';

export const selectUser = (state: StateType) => state[NameSpace.User].user;
export const selectUserAuthStatus = (state: StateType) => state[NameSpace.User].authStatus;
export const selectUsersReadyTrain = (state: StateType) => state[NameSpace.User].usersReadyTrain;
export const selectTrainingsCount = (state: StateType) => state[NameSpace.User].trainingsCount;
export const selectLocationFilter = (state: StateType) => state[NameSpace.User].locationFilter;
export const selectTrainTypeFilter = (state: StateType) => state[NameSpace.User].trainTypeFilter;
export const selectLevelFilter = (state: StateType) => state[NameSpace.User].levelFilter;
export const selectRoleFilter = (state: StateType) => state[NameSpace.User].roleFilter;
export const selectUsersList = (state: StateType) => state[NameSpace.User].usersList;
export const selectUsersTake = (state: StateType) => state[NameSpace.User].usersTake;
export const selectUsersTotalItems = (state: StateType) => state[NameSpace.User].usersTotalItems;
export const selectUserItem = (state: StateType) => state[NameSpace.User].userItem;
export const selectUserFriends = (state: StateType) => state[NameSpace.User].userFriends;
export const selectApplicationsList = (state: StateType) => state[NameSpace.User].applicationsList;
export const selectUserUpdateStatus = (state: StateType) => state[NameSpace.User].updateUserStatus;
export const selectNotifications = (state: StateType) => state[NameSpace.User].notifications;
export const selectLoadUsersReadyTrainStatus = (state: StateType) => state[NameSpace.User].loadUsersReadyTrainStatus;
export const selectSigninUserStatus = (state: StateType) => state[NameSpace.User].signinUserStatus;
export const selectAuthoriseUserStatus = (state: StateType) => state[NameSpace.User].authoriseUserStatus;
export const selectLoginUserStatus = (state: StateType) => state[NameSpace.User].loginUserStatus;
export const selectOrderTrainingsStatus = (state: StateType) => state[NameSpace.User].orderTrainingsStatus;
export const selectLoadAvailableTrainingsCountStatus = (state: StateType) => state[NameSpace.User].loadAvailableTrainingsCountStatus;
export const selectUseActiveTrainingsStatus = (state: StateType) => state[NameSpace.User].useActiveTrainingsStatus;
export const selectLoadUsersListStatus = (state: StateType) => state[NameSpace.User].loadUsersListStatus;
export const selectLoadUserFriendsStatus = (state: StateType) => state[NameSpace.User].loadUserFriendsStatus;
export const selectLoadUserItemStatus = (state: StateType) => state[NameSpace.User].loadUserItemStatus;
export const selectAddToFriendsStatus = (state: StateType) => state[NameSpace.User].addToFriendsStatus;
export const selectApplyPersonalTrainingStatus = (state: StateType) => state[NameSpace.User].applyPersonalTrainingStatus;
export const selectSubscribeNotificationsStatus = (state: StateType) => state[NameSpace.User].subscribeNotificationsStatus;
export const selectLoadUserItemTrainingsStatus = (state: StateType) => state[NameSpace.User].loadUserItemTrainingsStatus;
export const selectLoadUserApplicationsStatus = (state: StateType) => state[NameSpace.User].loadUserApplicationsStatus;
export const selectLoadAuthorApplicationsStatus = (state: StateType) => state[NameSpace.User].loadAuthorApplicationsStatus;
export const selectUpdateApplicationStatus = (state: StateType) => state[NameSpace.User].updateApplicationStatus;
export const selectLoadNotificationsStatus = (state: StateType) => state[NameSpace.User].loadNotificationsStatus;
