import { StateType } from '../../types';
import { NameSpace } from '../../const';
import { createSelector } from '@reduxjs/toolkit';

export const selectSpecialOffers = (state: StateType) => state[NameSpace.Training].specialOffers;
export const selectPopularTrainings = (state: StateType) => state[NameSpace.Training].popularTrainings;
export const selectChoiseTrainings = (state: StateType) => state[NameSpace.Training].choiseTrainings;
export const selectTrainingsList = (state: StateType) => state[NameSpace.Training].trainingsList;
export const selectTrainingsOrderedList = (state: StateType) => state[NameSpace.Training].trainingsOrderedList;
export const selectTake = (state: StateType) => state[NameSpace.Training].take;
export const selectPriceFilter = (state: StateType) => state[NameSpace.Training].priceFilter;
export const selectCaloriesFilter = (state: StateType) => state[NameSpace.Training].caloriesFilter;
export const selectRatingFilter = (state: StateType) => state[NameSpace.Training].ratingFilter;
export const selectTrainTypeFilter = (state: StateType) => state[NameSpace.Training].trainTypeFilter;
export const selectSortByOrder = (state: StateType) => state[NameSpace.Training].sortByOrder;
export const selectSortByField = (state: StateType) => state[NameSpace.Training].sortByField;
export const selectTotalItems = (state: StateType) => state[NameSpace.Training].totalItems;
export const selectTraining = (state: StateType) => state[NameSpace.Training].training;
export const selectTrainer = (state: StateType) => state[NameSpace.Training].trainer;
export const selectReviews = (state: StateType) => state[NameSpace.Training].reviews;
export const selectTrainingItem = (trainingId: string) => createSelector(selectTrainingsList, (trainingsList) => trainingsList.find((training) => training.id === trainingId));
export const selectDurationFilter = (state: StateType) => state[NameSpace.Training].durationFilter;
export const selectPostTrainingStatus = (state: StateType) => state[NameSpace.Training].postTrainingStatus;
export const selectIsActiveTrainings = (state: StateType) => state[NameSpace.Training].isActiveTrainings;
export const selectLoadSpecialOffersStatus = (state: StateType) => state[NameSpace.Training].loadSpecialOffersStatus;
export const selectLoadPopularTrainingsStatus = (state: StateType) => state[NameSpace.Training].loadPopularTrainingsStatus;
export const selectLoadChoiseTrainingsStatus = (state: StateType) => state[NameSpace.Training].loadChoiseTrainingsStatus;
export const selectLoadTrainingsStatus = (state: StateType) => state[NameSpace.Training].loadTrainingsStatus;
export const selectLoadTrainingsPurchasedStatus = (state: StateType) => state[NameSpace.Training].loadTrainingsPurchasedStatus;
export const selectLoadTrainingsOrderedStatus = (state: StateType) => state[NameSpace.Training].loadTrainingsOrderedStatus;
export const selectLoadTrainingStatus = (state: StateType) => state[NameSpace.Training].loadTrainingStatus;
export const selectUpdateTrainingStatus = (state: StateType) => state[NameSpace.Training].updateTrainingStatus;
export const selectLoadTrainerStatus = (state: StateType) => state[NameSpace.Training].loadTrainerStatus;
export const selectLoadReviewsStatus = (state: StateType) => state[NameSpace.Training].loadReviewsStatus;
export const selectPostReviewStatus = (state: StateType) => state[NameSpace.Training].postReviewStatus;
